apiVersion: v1
kind: Service
metadata:
  name: twtw-backend
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: twtw-backend
    component: twtw-backend
    tier: backend
  clusterIP: None
