version: "3"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - db
      - rabbitmq
    env_file: .env
    restart: always
    tty: true

  db:
    image: mysql
    container_name: db
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - backend
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    entrypoint: >
      /bin/bash -c "
        rabbitmq-server &
        sleep 20 && rabbitmq-plugins enable rabbitmq_web_stomp &
        tail -f /dev/null
      "
    env_file: .env
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    volumes:
      - data_rabbitmq:/rabbitmq
    networks:
      - backend
    restart: always
    tty: true

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - backend
    restart: always
    tty: true
  
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    restart: always
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    user: root
    ports:
      - 9090:9090
    networks:
      - backend
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_config:/etc/prometheus
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - backend

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    user: root
    ports:
      - 9093:9093
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    depends_on:
      - backend
      - prometheus
    networks:
      - backend

networks:
  backend:

volumes:
  data_rabbitmq: null
  prometheus_data: null
  prometheus_config: null
