apiVersion: apps/v1
kind: Deployment
metadata:
  name: twtw-db
spec:
  selector:
    matchLabels:
      app: twtw-db
      component: twtw-db
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: twtw-db
        component: twtw-db
        tier: backend
    spec:
      containers:
        - name: twtw-db
          image: mysql:8.0.33
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twtw-secret
                  key: database.password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: twtw-secret
                  key: database.schema
      volumes:
        - name: mysql-volume
          hostPath:
            path: /volume/data/twtw
