apiVersion: v1
kind: Service
metadata:
  name: twtw-db
spec:
  ports:
    - name: twtw-db
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: twtw-db
    component: twtw-db
  clusterIP: None
