version: "3"

services:
  db:
    image: mariadb:10
    ports:
      - 3306:3306
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always
networks:
  backend:
