global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'backend'
    scrape_interval: 5s
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
    - targets: ['backend:8080']
