server:
  servlet:
    context-path: /api/v1
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/TWTW
    username: root
    password: root!
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - classpath:application-env.yml
