server:
  servlet:
    context-path: /api/v1
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TWTW
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        auto_quote_keyword: true
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - classpath:application-env.yml
  rabbitmq:
    host: localhost
    port: 5672
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    default-property-inclusion: non_null
  flyway:
    url: jdbc:mysql://localhost:3306/TWTW
    enabled: true
    baseline-on-migrate: false
    user: root
    password: 1234
management:
  endpoints:
    web:
      exposure:
        include: ["metrics", "prometheus", "circuitbreakers", "circuitbreakerevents"]
  health:
    circuitbreakers:
      enabled: true
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureRateThreshold: 30
      waitDurationInOpenState: 10000
  instances:
    backend-a:
      base-config: default
    backend-b:
      base-config: default
    backend-c:
      base-config: default
    backend-d:
      base-config: default
