server:
  servlet:
    context-path: /api/v1
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/TWTW
    username: root
    password: 1234
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        auto_quote_keyword: true
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - classpath:application-env.yml
  rabbitmq:
    host: localhost
    port: 5672
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    default-property-inclusion: non_null
  flyway:
    url: jdbc:mariadb://localhost:3306/TWTW
    enabled: true
    baseline-on-migrate: false
    user: root
    password: 1234
