server:
  servlet:
    context-path: /api/v1
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        auto_quote_keyword: true
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      host: redis
      port: 6379
  jackson:
    default-property-inclusion: non_null
  cloud:
    gcp:
      credentials:
        location: ${CREDENTIALS_LOCATION}
      storage:
        credentials:
          location: ${CREDENTIALS_LOCATION}
        project-id: ${PROJECT_ID}
        bucket: ${BUCKET_NAME}
        storage-url: ${BUCKET_URL}
  flyway:
    url: jdbc:mariadb://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul
    enabled: true
    baseline-on-migrate: false
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: prometheus
jwt:
  secret: ${JWT_SECRET}
kakao-map:
  url: ${KAKAO_MAP_URL}
  key: ${KAKAO_MAP_KEY}
  header-prefix: ${KAKAO_MAP_HEADER}
naver-map:
  id: ${NAVER_MAP_ID}
  secret: ${NAVER_MAP_SECRET}
  url: ${NAVER_MAP_URL}
  header-client-id: ${NAVER_MAP_HEADER_ID}
  header-client-secret: ${NAVER_MAP_HEADER_SECRET}
tmap:
  app-key: ${TMAP_KEY}
  url: ${TMAP_URL}
firebase:
  location: ${FIREBASE_LOCATION}
