server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api/v1

spring:
  config:
    import:
      - classpath:application-env.yml

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=FALSE;MODE=MySQL;
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
        format_sql: true
    show-sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
  rabbitmq:
    listener:
      simple:
        auto-startup: false
      direct:
        auto-startup: false
      stream:
        auto-startup: false
    port: 5672
    host: localhost
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketMessagingAutoConfiguration
  data:
    redis:
      host: redis
      port: 6379
