server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api/v1

spring:
  config:
    import:
      - classpath:application-env.yml

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false;MODE=MySQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
        format_sql: true
    show-sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
