name: TWTW Backend CI
on:
  push:
    branches:
      - 'master'
    paths:
      - '**.java'
  pull_request:
    paths:
      - '**.java'
defaults:
  run:
    shell: bash
    working-directory: ./backend
jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Apply Environment Variables
      run: |
        mkdir -p src/test/resources
        echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > src/main/resources/application-env.yml
        find src

    - run: chmod +x gradlew
    - run: ./gradlew build -x test
    - run: ./gradlew jib

    - name: Test Coverage Report
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      with:
        paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "test coverage"
        min-coverage-overall: 60
        min-coverage-changed-files: 60
