name: TWTW Backend CI
on:
  push:
    paths:
      - '**.java'
  pull_request:
    paths:
      - '**.java'
defaults:
  run:
    shell: bash
    working-directory: ./backend
jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
    - run: chmod +x gradlew
    - run: ./gradlew build -x test
