name: TWTW Nginx Build
on:
  push:
    branches:
      - 'master'
    paths:
      - '**.conf'
defaults:
  run:
    shell: bash
    working-directory: ./nginx
jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Nginx Build and Push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/twtw-nginx:latest ./nginx
        docker push ${{ secrets.DOCKER_USERNAME }}/twtw-nginx:latest
